version: 2

sources:
  - name: rentals
    database: dvdrental
    schema: public
    tables:
      - name: payment
        identifier: payment
      - name: customer
        identifier: customer
  - name: payments
    database: dvdrental
    schema: public_test
    tables:
      - name: payments
        identifier: payments


